### PR TITLE
Switch to mdBook to generate GH pages

### PR DESCRIPTION
**Pull request by flodolo**

### CODE REVIEW

**Review by MikkCZ — COMMENTED** [review]
Looks good at first look. I will checkout the branch and try to play with the result locally, so I don't miss the same troubles as with the first repo.

**Review by MikkCZ — APPROVED** [review]
I walked through most of the pages and haven't found any broken link nor missing image assets. Good work.

**Comment by flodolo** [comment]
Thanks for taking the time. 

For future reference, I've used this [npm package](https://www.npmjs.com/package/broken-link-checker) to check for broken links. That's also how I found most of the broken links in the styleguides repo.

**Comment by MikkCZ** [comment]
Can we add it to `npm test`?

**Comment by flodolo** [comment]
We could, but we can't run it as part of the Travis, as far as I can think. Also, we have a bunch of issues open to fix broken links.

**Pull request merged**
