### PR TITLE
Add basic style guide for writing documents, update docs accordingly

### PR DESCRIPTION
**Pull request by flodolo**
Fixes #68

### CODE REVIEW

**Comment by flodolo** [comment]
You might want to start from this part, and look at the linked document.
https://github.com/mozilla-l10n/documentation/blob/style_guide/README.md#updating-the-documentation

The rest is just applying these rules to the existing documents.

**Comment by flodolo** [comment]
Recap of IRC discussion with Delphine. 

If you use Atom, you can install a package called [smart-quotes-plus](https://atom.io/packages/smart-quotes-plus) (go into Preferences, select Install on the left, search for the name and install it).

Then use ctrl+alt+' to swap all quotes to the correct ones (you can do it also on a selection of text). Make sure that you don't do that on a document that contain ' (e.g. code fragments). If you don't remember the shortcut, you can press alt+shift+p and search for smartquotes.

Not sure if we want something in the docs about this.

**Comment by peiying2** [comment]
I'd vote for including this tip in the doc.

**Review by Delphine — COMMENTED** [review]
Everything LGTM (may be interesting to have that Atom package link in the doc)

**Comment by flodolo** [comment]
Added note: https://github.com/mozilla-l10n/documentation/pull/69/commits/cddf34773322fb088d6d6d9113bd2fe757ba2c3f

Note that you should use the official review command (go in the `Files changed` tab, `Review changes`, approve changes) to mark the PR as good to go.

**Review by peiying2 — APPROVED** [review]
LGTM

**Comment by Delphine** [comment]
Looking good :D thanks!

**Review by Delphine — APPROVED** [review]

**Pull request merged**
