### PR TITLE
Add doc for strings review

### PR DESCRIPTION
**Pull request by flodolo**
See issue #112

### CODE REVIEW

**Review by Delphine — APPROVED** [review]
Makes sense - at least reading it ;) thanks for detailing out all this. Approving but definitely needs axel's review too for actual content.

**Comment by flodolo** [comment]
Thanks Delphine, I'll wait for Pike's review this week. We might end up changing it quite a bit, since this describes my way of testing the strings, but I'm afraid it's far from being the best for everyone.

**Comment by flodolo** [comment]
@Pike 
Do you want to add your general feedback before I try to change this doc a bit, for example removing the comparison with a localization repository?

**Comment by flodolo** [comment]
Per vidyo chat: I'm going to merge this, then we can iterate over it going forward.

**Pull request merged**
