### PR TITLE
(fixes #168) Delete appstores files

### LINKED ISSUE #168: Remove appstores documentation
We should wait for the project to be completely disabled in Pontoon, and comms out to localizers. But once that's done, we should remove the appstores section https://mozilla-l10n.github.io/documentation/products/appstores/index.html

#167 takes care of the tools part.

### PR DESCRIPTION
**Pull request by Delphine**

### CODE REVIEW

**Review by peiying2 — APPROVED** [review]
Looks good.

**Review by flodolo — CHANGES_REQUESTED** [review]
There have to be references to these pages, if nothing else in SUMMARY.md (but likely more).

I would suggest to search for `appstores`.

**Comment by Delphine** [comment]
I think those were all the instances left 🤞

**Comment by flodolo** [comment]
Added a couple more leftovers related to App Stores (but not strictly to these docs).

**Review by flodolo — APPROVED** [review]

**Pull request merged**
