### PR TITLE
Use Travis to build and deploy gh-pages

### PR DESCRIPTION
**Pull request by flodolo**
Had to fix some tag errors for Jekyll.

### CODE REVIEW

**Comment by flodolo** [comment]
@MikkCZ 
At this point you're the only one familiar with what is going on here, so I'll have to abuse you for reviews ;-)

Tested on [fork here](https://flodolo.github.io/documentation/).

**Review by MikkCZ — COMMENTED** [review]
Changes regarding the switch from `deploy.sh` to Travis look good. I will check the Django tags later. Please ping me if I forget to do it before Friday.

**Review by MikkCZ — COMMENTED** [review]
As noted the deploy code is good. However I wonder why the `{% raw %}` is in the markdown in the first place. If I understand the code snippets correctly, it actually does not belong there. When I remove it from the markdown completely, everything looks good.

**Comment by flodolo** [comment]
> However I wonder why the {% raw %} is in the markdown in the first place. If I understand the code snippets correctly, it actually does not belong there. When I remove it from the markdown completely, everything looks good.

It breaks GitHub page generation, because it's interpreted as a Jekyll directive 
http://tesoriere.com/2010/08/25/liquid-code-in-a-liquid-template-with-jekyll/

On GitBook it won't be rendered, sadly it will show up in GitHub.

**Comment by flodolo** [comment]
The error you get is
https://help.github.com/articles/page-build-failed-unknown-tag-error/

**Comment by MikkCZ** [comment]
So the trouble is actually not in the `{% raw %}` tag, but in the code that's inside the code block, because Jekyll tried to process it after the deploy to `gh-pages`? In that case adding [`.nojekyll`](https://blog.github.com/2009-12-29-bypassing-jekyll-on-github-pages/) should disable it. As we do not use Jekyll, we may want to disable it for all repos so the problem won't reappear in the future.

**Comment by flodolo** [comment]
> So the trouble is actually not in the {% raw %} tag, but in the code that's inside the code block, because Jekyll tried to process it after the deploy to gh-pages?

Yes

> In that case adding .nojekyll should disable it. As we do not use Jekyll, we may want to disable it for all repos so the problem won't reappear in the future.

OK, I need to try this.

The only case where this happens is this repo, others won't have need to use fragment of Django code, but it won't hurt to add it.

**Comment by flodolo** [comment]
> OK, I need to try this.

Great, looks like it's working. Travis built, and GitHub didn't complain about Pages generation

**Review by MikkCZ — APPROVED** [review]

**Comment by flodolo** [comment]
Thanks Michal!

**Pull request merged**
