### PR TITLE
Update production deployment docs with manual git instruction steps

### PR DESCRIPTION
**Pull request by alexgibson**

### CODE REVIEW

**Comment by alexgibson** [comment]
@flodolo r?

**Comment by alexgibson** [comment]
By the way, I notice the SSL cert for https://l10n.mozilla-community.org/langchecker/ exprired today.

**Comment by flodolo** [comment]
> By the way, I notice the SSL cert for https://l10n.mozilla-community.org/langchecker/ exprired today.

Thanks, that's managed by community IT, and I need to figure out who to talk to.

**Review by flodolo — APPROVED** [review]
Thanks for updating it 👍

**Pull request merged**
