### PR TITLE
(fixes #171) Update docs for Firefox

### LINKED ISSUE #171: Shipping Firefox: update documentation and bugogram
[Bugogram](https://wiki.mozilla.org/index.php?title=L10n:Bugogram):
- Remove DXR mention from the hg repository creation.

Documentation:
- Changes to Ship It are not needed anymore
- Still need to make sure product-details has the language name in https://github.com/mozilla-releng/product-details/
- AMO admin address (mozilla.com, nor org)
- Add pre-beta checks:
  - MOZ_LANG_TITLE in defines.inc

### PR DESCRIPTION
**Pull request by flodolo**

### CODE REVIEW

**Comment by flodolo** [comment]
~For some reasons I can't set @mozilla-l10n/pm-group as a reviewer~

Fixed via support: the team needs to be added with at least read access to each repo…

**Comment by flodolo** [comment]
Ignore the Travis failure. It's not an issue with the doc, something else broke with the rust installation, and it should fix itself later.

**Comment by flodolo** [comment]
> Ignore the Travis failure. It's not an issue with the doc, something else broke with the rust installation, and it should fix itself later.

That should be fixed by (waiting for Travis there)
https://github.com/mozilla-l10n/documentation/pull/177

**Review by Delphine — APPROVED** [review]
This LGTM

**Comment by flodolo** [comment]
Thanks 🦄

**Pull request merged**
