### PR TITLE
Reorganize content, remove documentation for localizers (fixes #81)

### LINKED ISSUE #81: Split user facing documentation into a different repository
* [x] Create a new repository
* [ ] Move existing user facing documentation to this repository

### PR DESCRIPTION
**Pull request by flodolo**

### CODE REVIEW

**Comment by flodolo** [comment]
The best way to check this is to take a quick look at the diff, then browse the documentation starting from here
https://github.com/mozilla-l10n/documentation/tree/move_userdocs

**Review by peiying2 — APPROVED** [review]
I can only verify the sections I use due to familiarity.  They look good.

**Review by Delphine — APPROVED** [review]
Thanks flod this looks good! I'm wondering if setting up search plugins could also be a localizer-facing doc. But those cases in practice are so rare, that I don't think this matters too much.

**Comment by flodolo** [comment]
Thanks for checking. Given that now you need to go through mozilla-central, I doubt we'll have localizers doing it. It will be an exception, and sending them to the other doc should be enough.

**Pull request merged**
